# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-02-19 22:56
from __future__ import unicode_literals

from django.db import migrations, models
import private_media.storages


class Migration(migrations.Migration):

    dependencies = [
        ('archivos', '0002_archivo_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivo',
            name='archivo',
            field=models.FileField(storage=private_media.storages.PrivateMediaStorage(), upload_to=b''),
        ),
    ]
