# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categorias', '0002_auto_20160727_0914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='categoria',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
