# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-27 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('permisos', '0002_auto_20160726_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='permiso',
            name='emma',
            field=models.BooleanField(default=True),
        ),
    ]
